### ISSUE TITLE
:ShowBase(warning): Unable to open 'onscreen' window.

### ISSUE THREAD

**Issue by Nockda** [heyuanYao-pku/Control-VAE#4]
When I type

```
python PlayGround\random_playground.py
```

This error occurred.
My env is Ubuntu 20.04.2 ARM64
I tried the same as readme
Do you have any idea to solve this?

GPU not detected. Defaulting to CPU.
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
:display:glxdisplay(error): Could not find a usable pixel format.
:display:glxdisplay(error): No GLX context: cannot open window.
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:gsg:glgsg(warning): Unable to query GL_VENDOR
:display:gsg:glgsg(warning): Unable to query GL_RENDERER
:display:gsg:glgsg(warning): Unable to query GL_VERSION
:display:gsg:glgsg(error): Unable to detect OpenGL version
:display:egldisplay(error): Failed to find or initialize a suitable EGL display connection.
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "PlayGround/random_playground.py", line 221, in <module>
    playground = RandomPlayground(323, 57, 120, env, **args)
  File "PlayGround/random_playground.py", line 56, in __init__
    self.init_viewer()
  File "PlayGround/random_playground.py", line 67, in init_viewer
    self.panda_server = PandaServerBase()
  File "/home/parallels/Downloads/Control-VAE-main/PlayGround/panda_server_base.py", line 54, in __init__
    super().__init__(fStartDirect, windowType)
  File "/home/parallels/miniconda3/envs/control-vae/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 341, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "/home/parallels/miniconda3/envs/control-vae/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1026, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "/home/parallels/miniconda3/envs/control-vae/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 1061, in openMainWindow
    self.openWindow(*args, **kw)
  File "/home/parallels/miniconda3/envs/control-vae/lib/python3.8/site-packages/direct/showbase/ShowBase.py", line 806, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

**Comment by heyuanYao-pku** [comment]
sorry for late.
It seems to be the problem of the installaion of panda3d....
Maybe you can try to reinstall it with pip.

**Comment by heyuanYao-pku** [comment]
seems not to be a problem with this repo, closed.
